# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form8.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 801)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(230, 120, 601, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.subCategorieCB = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subCategorieCB.sizePolicy().hasHeightForWidth())
        self.subCategorieCB.setSizePolicy(sizePolicy)
        self.subCategorieCB.setMinimumSize(QtCore.QSize(0, 0))
        self.subCategorieCB.setSizeIncrement(QtCore.QSize(0, 0))
        self.subCategorieCB.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.subCategorieCB.setCurrentText("")
        self.subCategorieCB.setMaxVisibleItems(10000)
        self.subCategorieCB.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.subCategorieCB.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.subCategorieCB.setModelColumn(0)
        self.subCategorieCB.setObjectName("subCategorieCB")
        self.gridLayout.addWidget(self.subCategorieCB, 0, 1, 1, 1)
        self.subcategory_label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.subcategory_label_3.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.subcategory_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.subcategory_label_3.setObjectName("subcategory_label_3")
        self.gridLayout.addWidget(self.subcategory_label_3, 0, 0, 1, 1)
        self.genereazaGraph_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.genereazaGraph_Button.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.genereazaGraph_Button.setObjectName("genereazaGraph_Button")
        self.gridLayout.addWidget(self.genereazaGraph_Button, 1, 1, 1, 1)
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(10, -10, 1011, 125))
        self.title.setStyleSheet("font: 87 26pt \"Segoe UI Black\";")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(True)
        self.title.setObjectName("title")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 270, 961, 521))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.chart_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.chart_layout.setContentsMargins(0, 0, 0, 0)
        self.chart_layout.setObjectName("chart_layout")
        self.subcategory_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.subcategory_label_2.setGeometry(QtCore.QRect(10, 80, 981, 37))
        self.subcategory_label_2.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.subcategory_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.subcategory_label_2.setObjectName("subcategory_label_2")
        self.export_btn = QtWidgets.QPushButton(self.centralwidget)
        self.export_btn.setGeometry(QtCore.QRect(795, 10, 191, 33))
        self.export_btn.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.export_btn.setObjectName("export_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.subcategory_label_3.setText(_translate("MainWindow", "Sub Categorie Produs"))
        self.genereazaGraph_Button.setText(_translate("MainWindow", "Genereaza Graph"))
        self.title.setText(_translate("MainWindow", "CAIA"))
        self.subcategory_label_2.setText(_translate("MainWindow", "Evidentierea ponderii vanzarilor pe fiecare produs in parte, in total vanzari"))
        self.export_btn.setText(_translate("MainWindow", "Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
