# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form5.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 801)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(10, 0, 1011, 125))
        self.title.setStyleSheet("font: 87 26pt \"Segoe UI Black\";")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(True)
        self.title.setObjectName("title")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 310, 961, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.chart_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.chart_layout.setContentsMargins(0, 0, 0, 0)
        self.chart_layout.setObjectName("chart_layout")
        self.slider_value = QtWidgets.QLabel(self.centralwidget)
        self.slider_value.setGeometry(QtCore.QRect(910, 250, 41, 31))
        self.slider_value.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.slider_value.setAlignment(QtCore.Qt.AlignCenter)
        self.slider_value.setObjectName("slider_value")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 120, 761, 163))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.subCategory_CB = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subCategory_CB.sizePolicy().hasHeightForWidth())
        self.subCategory_CB.setSizePolicy(sizePolicy)
        self.subCategory_CB.setMinimumSize(QtCore.QSize(0, 0))
        self.subCategory_CB.setSizeIncrement(QtCore.QSize(0, 0))
        self.subCategory_CB.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.subCategory_CB.setCurrentText("")
        self.subCategory_CB.setMaxVisibleItems(10000)
        self.subCategory_CB.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.subCategory_CB.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.subCategory_CB.setModelColumn(0)
        self.subCategory_CB.setObjectName("subCategory_CB")
        self.gridLayout.addWidget(self.subCategory_CB, 0, 1, 1, 1)
        self.genereazaGraph_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.genereazaGraph_Button.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.genereazaGraph_Button.setObjectName("genereazaGraph_Button")
        self.gridLayout.addWidget(self.genereazaGraph_Button, 1, 1, 1, 1)
        self.subcategory_label = QtWidgets.QLabel(self.layoutWidget)
        self.subcategory_label.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.subcategory_label.setAlignment(QtCore.Qt.AlignCenter)
        self.subcategory_label.setObjectName("subcategory_label")
        self.gridLayout.addWidget(self.subcategory_label, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(0, 30))
        self.horizontalSlider.setMaximumSize(QtCore.QSize(759, 30))
        self.horizontalSlider.setSizeIncrement(QtCore.QSize(60, 0))
        self.horizontalSlider.setMaximum(60)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(0)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_2.addWidget(self.horizontalSlider, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        self.export_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_button.setGeometry(QtCore.QRect(710, 10, 296, 33))
        self.export_button.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.export_button.setObjectName("export_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "CAIA"))
        self.slider_value.setText(_translate("MainWindow", "0"))
        self.genereazaGraph_Button.setText(_translate("MainWindow", "Genereaza Graph"))
        self.subcategory_label.setText(_translate("MainWindow", "Selecteaza Sub Categorie"))
        self.label.setText(_translate("MainWindow", "Numarul de produse afisate"))
        self.export_button.setText(_translate("MainWindow", "Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
