# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1026, 845)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(10, 20, 1011, 125))
        self.title.setStyleSheet("font: 87 26pt \"Segoe UI Black\";")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(True)
        self.title.setObjectName("title")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 280, 941, 551))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.chart_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.chart_layout.setContentsMargins(0, 0, 0, 0)
        self.chart_layout.setObjectName("chart_layout")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 150, 793, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.parameters_grid = QtWidgets.QGridLayout(self.layoutWidget)
        self.parameters_grid.setContentsMargins(0, 0, 0, 0)
        self.parameters_grid.setObjectName("parameters_grid")
        self.frecventaCategoriilorRB = QtWidgets.QRadioButton(self.layoutWidget)
        self.frecventaCategoriilorRB.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.frecventaCategoriilorRB.setObjectName("frecventaCategoriilorRB")
        self.parameters_grid.addWidget(self.frecventaCategoriilorRB, 1, 2, 1, 1)
        self.totalulProfVanzPeSubCategorieRB = QtWidgets.QRadioButton(self.layoutWidget)
        self.totalulProfVanzPeSubCategorieRB.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.totalulProfVanzPeSubCategorieRB.setObjectName("totalulProfVanzPeSubCategorieRB")
        self.parameters_grid.addWidget(self.totalulProfVanzPeSubCategorieRB, 0, 1, 1, 1)
        self.distributiasubCategoriilorRB = QtWidgets.QRadioButton(self.layoutWidget)
        self.distributiasubCategoriilorRB.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.distributiasubCategoriilorRB.setObjectName("distributiasubCategoriilorRB")
        self.parameters_grid.addWidget(self.distributiasubCategoriilorRB, 0, 2, 1, 1)
        self.genereazaGraphButton = QtWidgets.QPushButton(self.layoutWidget)
        self.genereazaGraphButton.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.genereazaGraphButton.setObjectName("genereazaGraphButton")
        self.parameters_grid.addWidget(self.genereazaGraphButton, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "CAIA"))
        self.frecventaCategoriilorRB.setText(_translate("MainWindow", "Frecventa categoriilor"))
        self.totalulProfVanzPeSubCategorieRB.setText(_translate("MainWindow", "Totalul profitului si a vanzarilor pe sub categorie"))
        self.distributiasubCategoriilorRB.setText(_translate("MainWindow", "Distributia sub categoriilor"))
        self.genereazaGraphButton.setText(_translate("MainWindow", "Genereaza Graph"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
