# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1215, 686)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setEnabled(True)
        self.title.setGeometry(QtCore.QRect(130, -10, 781, 125))
        self.title.setStyleSheet("font: 87 26pt \"Segoe UI Black\";")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(True)
        self.title.setObjectName("title")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(800, 370, 381, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.chart_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.chart_layout.setContentsMargins(0, 0, 0, 0)
        self.chart_layout.setObjectName("chart_layout")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 100, 761, 561))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.map_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.map_layout.setContentsMargins(0, 0, 0, 0)
        self.map_layout.setObjectName("map_layout")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(830, 130, 331, 107))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.combobox = QtWidgets.QComboBox(self.layoutWidget)
        self.combobox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox.sizePolicy().hasHeightForWidth())
        self.combobox.setSizePolicy(sizePolicy)
        self.combobox.setMinimumSize(QtCore.QSize(0, 0))
        self.combobox.setSizeIncrement(QtCore.QSize(0, 0))
        self.combobox.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.combobox.setCurrentText("West")
        self.combobox.setMaxVisibleItems(10000)
        self.combobox.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.combobox.setModelColumn(0)
        self.combobox.setObjectName("combobox")
        self.combobox.addItem("")
        self.combobox.addItem("")
        self.combobox.addItem("")
        self.combobox.addItem("")
        self.gridLayout.addWidget(self.combobox, 1, 0, 1, 1)
        self.genereazaGraph_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.genereazaGraph_Button.setStyleSheet("font: 14pt \"Nirmala UI Semilight\";")
        self.genereazaGraph_Button.setObjectName("genereazaGraph_Button")
        self.gridLayout.addWidget(self.genereazaGraph_Button, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CAIA"))
        self.title.setText(_translate("MainWindow", "CAIA"))
        self.checkBox.setText(_translate("MainWindow", "Zoom regiune selectata"))
        self.combobox.setItemText(0, _translate("MainWindow", "West"))
        self.combobox.setItemText(1, _translate("MainWindow", "South"))
        self.combobox.setItemText(2, _translate("MainWindow", "Central"))
        self.combobox.setItemText(3, _translate("MainWindow", "East"))
        self.genereazaGraph_Button.setText(_translate("MainWindow", "Vizualizeaza"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
